# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-06-19 19:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('octopus', '0002_auto_20190619_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='lightbulb',
            name='average200',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lightbulb',
            name='average250',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lightbulb',
            name='average300',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lightbulb',
            name='average350',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lightbulb',
            name='average400',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lightbulb',
            name='depth',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lightbulb',
            name='height',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lightbulb',
            name='performance200',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lightbulb',
            name='performance250',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lightbulb',
            name='performance300',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lightbulb',
            name='performance350',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lightbulb',
            name='performance400',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lightbulb',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lightbulb',
            name='stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lightbulb',
            name='weight',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lightbulb',
            name='width',
            field=models.IntegerField(default=0),
        ),
    ]
