# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-06-19 19:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('octopus', '0003_auto_20190619_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lightbulb',
            name='depth',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='lightbulb',
            name='height',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='lightbulb',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='lightbulb',
            name='width',
            field=models.FloatField(default=0),
        ),
    ]
